### ISSUE TITLE
bug (core): disabled button does not have the correct color

### ISSUE THREAD

**Issue by Sukaato** [CheeseGrinder/poppy-ui#35]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/cheese-grinder/poppy-ui/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://github.com/cheese-grinder/poppy-ui/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/cheese-grinder/ionic-framework/issues) that already report this problem, without success.

### Poppy UI Version

v1.x

### Current Behavior

Text and border does not have a visible color when disabled

```css
:host([disabled])>button:disabled {
    --background: oklch(var(--neutral-oklch, 32.1785% 0.02476 255.701624) / 0.2);
    --color: oklch(var(--base-content-oklch, 27.8078% 0.029596 256.847952) / 0.2);
    pointer-events: none;
}
```

`--color` is not used

![image](https://github.com/user-attachments/assets/92a91b5b-39b0-45ba-a7a9-958c657d8d95)

### Expected Behavior

Have a visible disabled button

### Steps to Reproduce

1. Add button disabled / disabeld outlined
2. Cant see the button on dark theme
