### ISSUE TITLE
bug (core): can not select type on part in css

### ISSUE THREAD

**Issue by Sukaato** [CheeseGrinder/poppy-ui#40]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/cheese-grinder/poppy-ui/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://github.com/cheese-grinder/poppy-ui/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/cheese-grinder/ionic-framework/issues) that already report this problem, without success.

### Poppy UI Version

v1.x

### Current Behavior

Can not select input type with `::part` in the selector

### Expected Behavior

can select the input by type

- reflect the type on pop-input
- add a dynamic part
- or both

### Steps to Reproduce

```scss
pop-input {
  //           not working with ::part
  //                    v 
  &::part(native)[type=password]::placeholder {
    letter-spacing: 2px;
    color: oklch(var(--base-content-oklch) / .4);
  }
}
```
